# Generated by Django 5.2.1 on 2025-06-04 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('cash', '현금/예금'), ('stock', '주식'), ('real_estate', '부동산'), ('loan', '대출'), ('pension', '연금'), ('other', '기타')], max_length=20, verbose_name='자산 유형')),
                ('asset_name', models.CharField(max_length=100, verbose_name='자산명')),
                ('amount', models.DecimalField(decimal_places=0, help_text='부채는 음수로 입력', max_digits=15, verbose_name='평가금액')),
                ('snapshot_date', models.DateField(verbose_name='기록날짜')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자산 스냅샷',
                'verbose_name_plural': '자산 스냅샷들',
                'db_table': 'asset_snapshot',
                'ordering': ['-snapshot_date', 'asset_type', 'asset_name'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='asset_snaps_user_id_98fb4f_idx'), models.Index(fields=['user', 'asset_type'], name='asset_snaps_user_id_b595e4_idx')],
                'unique_together': {('user', 'asset_type', 'asset_name', 'snapshot_date')},
            },
        ),
    ]
