# Generated by Django 5.2.1 on 2025-06-04 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='분류명')),
                ('category_type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10, verbose_name='분류 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='상위 분류')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '분류',
                'verbose_name_plural': '분류들',
                'db_table': 'category',
                'indexes': [models.Index(fields=['user', 'category_type'], name='category_user_id_454d93_idx'), models.Index(fields=['parent'], name='category_parent__869b08_idx')],
                'unique_together': {('name', 'parent', 'user')},
            },
        ),
    ]
