#!/bin/bash
# GitHub 저장소 분리 스크립트 (참고용)

echo "⚠️  이 스크립트는 참고용입니다. 실행하기 전에 백업하세요!"
echo ""
echo "저장소 분리 방법:"
echo ""
echo "1. 백엔드 저장소 생성:"
echo "   cd /tmp"
echo "   git clone https://github.com/your-username/household-budget.git household-budget-backend"
echo "   cd household-budget-backend"
echo "   git filter-repo --path backend/ --path-rename backend/:"
echo "   git remote add origin https://github.com/your-username/household-budget-backend.git"
echo "   git push -u origin main"
echo ""
echo "2. 프론트엔드 저장소 생성:"
echo "   cd /tmp"
echo "   git clone https://github.com/your-username/household-budget.git household-budget-frontend"
echo "   cd household-budget-frontend"
echo "   git filter-repo --path frontend/ --path-rename frontend/:"
echo "   git remote add origin https://github.com/your-username/household-budget-frontend.git"
echo "   git push -u origin main"
echo ""
echo "⚠️  주의: git filter-repo 설치 필요: pip install git-filter-repo"
