# Generated by Django 5.2.1 on 2025-06-04 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='거래일')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='금액')),
                ('transaction_type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10, verbose_name='거래 타입')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('account', '계좌이체')], max_length=20, verbose_name='결제수단')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='categories.category', verbose_name='분류')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '거래',
                'verbose_name_plural': '거래들',
                'db_table': 'transaction',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='transaction_user_id_202735_idx'), models.Index(fields=['user', 'transaction_type'], name='transaction_user_id_9e98ba_idx'), models.Index(fields=['category'], name='transaction_categor_c453c0_idx')],
            },
        ),
    ]
